USE ROLE SYSADMIN;


USE WAREHOUSE COMPUTE_WH;


DROP DATABASE IF EXISTS RetailDataAnalyticsDB;


CREATE DATABASE Retail_Data_Analytics_DB;


USE DATABASE Retail_Data_Analytics_DB;


CREATE OR REPLACE SCHEMA bronze;
CREATE OR REPLACE SCHEMA silver;
CREATE OR REPLACE SCHEMA gold;

